export const GET_USER_REQUEST="GET_USER_REQUEST"
export const GET_USER_SUCCESS="GET_USER_SUCCESS"
export const GET_USER_ERROR="GET_USER_ERROR"


export const POST_USER_REQUEST="POST_USER_REQUEST"
export const POST_USER_SUCCESS="POST_USER_SUCCESS"
export const POST_USER_ERROR="POST_USER_ERROR"


